### ISSUE TITLE
incognito: true does not work with --no-headless locally, crashes on flood.io

### ISSUE THREAD

**Issue by dorrogeray** [flood-io/element#106]
**Describe the bug**
--no-headless does not work with incognito: true
Incognito mode also crashes on flood.io.

**To Reproduce**
1. In your test setting, set `incognito: true`
2. Run test locally with `element run test.ts --no-headless`

**Expected behavior**

**Error log**
```
jb@jb-ntb:~/projects/xxx/test/performance (story/performance-tests)$ element run test.ts --no-headless --verbose
+0s info: workRootPath: /home/jb/projects/xxx/test/performance/tmp/element-results/test/2020-02-09T205858.531Z
+0s info: testDataPath: /home/jb/projects/xxx/test/performance
+0s debug: Loading test script: test.ts
Module resolve paths: node_modules

✔ Script Compiler
  Compiled successfully in 161.76ms

{
  args: [ '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage' ],
  handleSIGINT: false,
  headless: false,
  devtools: false,
  chromeVersion: 'puppeteer',
  sandbox: true,
  timeout: 60000,
  ignoreHTTPSErrors: false,
  debug: true
}
+0s debug: Test loop count set to 1 iterations
+0s debug: Settings: {
  "waitUntil": false,
  "duration": -1,
  "loopCount": 1,
  "stepDelay": 6,
  "screenshotOnFailure": true,
  "clearCookies": true,
  "clearCache": false,
  "waitTimeout": 30,
  "responseTimeMeasurement": "step",
  "consoleFilter": [],
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36",
  "device": "Chrome Desktop Large",
  "ignoreHTTPSErrors": false,
  "chromeVersion": "puppeteer",
  "blockedDomains": [],
  "incognito": true,
  "name": "",
  "description": "",
  "disableCache": false,
  "extraHTTPHeaders": {},
  "launchArgs": [
    "--no-sandbox",
    "--disable-gpu",
    "--disable-dev-shm-usage"
  ]
}
+0s info: Starting iteration 1
+0s error: [Iteration: 1] Error in Runner Loop: Error: Protocol error (Target.createTarget): Target closed.
Error: Protocol error (Target.createTarget): Target closed.
    at /home/jb/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:73:12)
    at Browser._createPageInContext (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Browser.js:174:47)
    at BrowserContext.newPage (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Browser.js:367:26)
    at PuppeteerClient.<anonymous> (/home/jb/.config/yarn/global/node_modules/@flood/element-core/dist/src/driver/Puppeteer.js:77:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jb/.config/yarn/global/node_modules/@flood/element-core/dist/src/driver/Puppeteer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
+0s error: flood element error: Protocol error (Target.createTarget): Target closed.
+0s debug: Error: Protocol error (Target.createTarget): Target closed.
    at /home/jb/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:73:12)
    at Browser._createPageInContext (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Browser.js:174:47)
    at BrowserContext.newPage (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Browser.js:367:26)
    at PuppeteerClient.<anonymous> (/home/jb/.config/yarn/global/node_modules/@flood/element-core/dist/src/driver/Puppeteer.js:77:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jb/.config/yarn/global/node_modules/@flood/element-core/dist/src/driver/Puppeteer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
+0s debug: Error: Protocol error (Target.createTarget): Target closed.
    at /home/jb/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Connection.js:73:12)
    at Browser._createPageInContext (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Browser.js:174:47)
    at BrowserContext.newPage (/home/jb/.config/yarn/global/node_modules/puppeteer/lib/Browser.js:367:26)
    at PuppeteerClient.<anonymous> (/home/jb/.config/yarn/global/node_modules/@flood/element-core/dist/src/driver/Puppeteer.js:77:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jb/.config/yarn/global/node_modules/@flood/element-core/dist/src/driver/Puppeteer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node.js version: 12.13
 - Version 1.0.10-beta.45

**Additional context**
This also causes the flood output to be like this:
![image](https://user-images.githubusercontent.com/4999006/74110006-071a7a80-4b89-11ea-9ec7-f6a8c466411a.png)
![image](https://user-images.githubusercontent.com/4999006/74110019-18fc1d80-4b89-11ea-988d-2620d3630575.png)

**Comment by ivanvanderbyl** [comment]
Thanks for reporting. We'll try to replicate this and get it fixed.

**Comment by ivanvanderbyl** [comment]
@dorrogeray this was a bug in Puppeteer, I've updated everything and it should now be fixed in the latest release. You can upgrade by installing `element-cli@latest`
