### ISSUE TITLE
Error: Cannot find module '@flood/element/api'

### ISSUE THREAD

**Issue by MicHubs** [flood-io/element#140]
**Describe the bug**

**To Reproduce**
1. attempting to install element on mac I get the following errors 

Get it by running brew upgrade element
> Error! An unexpected error occurred!
  Error: Cannot find module '@flood/element/api'
Require stack:
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/cmd/plan.js
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/node_modules/yargs/index.js
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/element.js
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/cmd/plan.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19) Error: Cannot find module '@flood/element/api'
Require stack:
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/cmd/plan.js
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/node_modules/yargs/index.js
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/element.js
- /usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/cmd/plan.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

**Expected behavior**
no errors 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Node.js version: [e.g. 9.4]
 - Version [e.g. 1.0.2]

**Additional context**

**Comment by ivanvanderbyl** [comment]
Hi @MicHubs — it looks like an issue with our Homebrew builds. Can you try uninstalling it with brew and reinstalling with npm or yarn? `yarn global add element-cli`

**Comment by enriquecss** [comment]
Hi 

I tried with npm and same error, let me try using yarn.

Thanks

**Comment by ivanvanderbyl** [comment]
If you're still getting the same error, can you check that the stack trace doesn't include lines like this:

```
usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli
```

That indicates it's still loading the brew package, meaning it wasn't uninstalled correctly.

**Comment by HieuLeKMS** [comment]
This issue has been fixed by fixing the issue with Element's Homebrew builds. I'll close this issue.
