### ISSUE TITLE
Error: Cannot find module '@flood/element/api'

### ISSUE THREAD

**Issue by enriquecss** [flood-io/element#141]
**Describe the bug**
After the following instruction: 
brew install flood-io/taps/element

I tried to run element --version getting following error:
Error: Cannot find module '@flood/element/api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/cmd/plan.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) Error: Cannot find module '@flood/element/api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/Cellar/element/1.0.8/libexec/lib/node_modules/@flood/element-cli/dist/src/cmd/plan.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.m

**To Reproduce**
1. run brew install flood-io/taps/element

**Expected behavior**
element flood must be installed correctly 

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Node.js version: v10.15.3
 - Version NA

**Comment by ivanvanderbyl** [comment]
Hi @enriquecss, please see the solution in #140
