### ISSUE TITLE
isDisplayed() method is always true even if the actual xPath locator (element) is not available on the screen

### ISSUE THREAD

**Issue by natarajsph** [flood-io/element#255]
> Error! An unexpected error occurred!
  Error
    at ElementHandle.<anonymous> (/Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:58:23)
    at Generator.next (<anonymous>)
    at /Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:13:12)
    at ElementHandle.descriptor.value (/Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:56:20)
    at Object.base.apply (/Users/nataraj/Desktop/element_new_eshop/node_modules/vm2/lib/contextify.js:620:32)
    at new_eshop.ts:137:21
    at Generator.next (<anonymous>)
    at fulfilled (new_eshop.ts:106:58) Error
    at ElementHandle.<anonymous> (/Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:58:23)
    at Generator.next (<anonymous>)
    at /Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:13:12)
    at ElementHandle.descriptor.value (/Users/nataraj/Desktop/element_new_eshop/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:56:20)
    at Object.base.apply (/Users/nataraj/Desktop/element_new_eshop/node_modules/vm2/lib/contextify.js:620:32)
    at new_eshop.ts:137:21
    at Generator.next (<anonymous>)
    at fulfilled (new_eshop.ts:106:58)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md
PITHFLTLSHYL881:element_new_eshop nataraj$

**Comment by natarajsph** [comment]
raised by mistake
