### ISSUE TITLE
"Error: EEXIST: file already exists" when running the test

### ISSUE THREAD

**Issue by AlexeyAnischenko** [flood-io/element#26]
Going through steps in https://github.com/flood-io/element/blob/master/packages/cli/README.md#element-run
to run my first floodio-element test.

Installed NodeJS + all the tools ,installed element-cli,
created project files with "element init C:\Java\nodejs\projects\floodio\avatest"

And then it failed to run locally, please see the console log below.

Windows10-64, admin console:
--------------------------------------------------
c:\Java\nodejs\projects\floodio\avatest>node --version
v10.13.0

c:\Java\nodejs\projects\floodio\avatest>element --version
1.0.2

c:\Java\nodejs\projects\floodio\avatest>element run test.ts --verbose
+0s info: workRootPath: c:\Java\nodejs\projects\floodio\avatest\tmp\element-results\test\2018-11-13T12:12:00.753Z
+0s info: testDataPath: c:\Java\nodejs\projects\floodio\avatest
> Error! An unexpected error occurred!
  Error: EEXIST: file already exists, mkdir 'c:\Java\nodejs\projects\floodio\avatest\tmp\element-results\test'
    at Object.mkdirSync (fs.js:750:3)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17) Error: EEXIST: file already exists, mkdir 'c:\Java\nodejs\projects\floodio\avatest\tmp\element-results\test'
    at Object.mkdirSync (fs.js:750:3)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js:78:17)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md
----------------------------

**Comment by AlexeyAnischenko** [comment]
same with Node 11.1.0:

C:\Java\apache-jmeter-5.0\bin>node --version
v11.1.0

C:\Java\apache-jmeter-5.0\bin>element --version
1.0.2

C:\Java\nodejs\projects\floodio\avatest>element run test.ts
+0s info: workRootPath: C:\Java\nodejs\projects\floodio\avatest\tmp\element-results\test\2018-11-14T16:30:
+0s info: testDataPath: C:\Java\nodejs\projects\floodio\avatest
> Error! An unexpected error occurred!
  Error: EEXIST: file already exists, mkdir 'C:\Java\nodejs\projects\floodio\avatest\tmp\element-results\t
    at Object.mkdirSync (fs.js:773:3)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
e already exists, mkdir 'C:\Java\nodejs\projects\floodio\avatest\tmp\element-results\test'
    at Object.mkdirSync (fs.js:773:3)
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
    at sync (C:\Users\ava\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\mkdirp\index.js
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

**Comment by ivanvanderbyl** [comment]
Thanks for reporting @AlexeyAnischenko — this looks like a bug in how we create directories on windows. Please delete the file in question and try it again. We'll release a patch for this soon.

**Comment by AlexeyAnischenko** [comment]
Tried to delete just the "test" folder as you recommended, and then the whole "tmp" folder - no luck both times, same results

**Comment by ivanvanderbyl** [comment]
Okay, thanks for letting us know. We'll release a patch shortly.

**Comment by AlexeyAnischenko** [comment]
Confirming it as fixed in 1.03, thx!
