### ISSUE TITLE
Release v1.3.1 breaks iterations

### ISSUE THREAD

**Issue by prodigy7** [flood-io/element#264]
**Describe the bug**
Today I was forced to upgrade to 1.3.1 to continue using my test scripts. After doing that, my scripts doesn't longer run without errors. I've 2 scripts with different count of steps, but in both cases the scripts stops with a error, when the second iteration should start.

```
+46s info: Iteration completed in 44s (walltime)
+46s info: Starting iteration 2
> Error! An unexpected error occurred!
  Error
    at ElementHandle.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:58:23)
    at Generator.next (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:13:12)
    at ElementHandle.descriptor.value (/usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:56:20)
    at Object.base.apply (/usr/local/share/.config/yarn/global/node_modules/vm2/lib/contextify.js:620:32)
    at ./full.ts:425:25
    at Generator.next (<anonymous>)
    at fulfilled (./full.ts:106:58) Error
    at ElementHandle.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:58:23)
    at Generator.next (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:13:12)
    at ElementHandle.descriptor.value (/usr/local/share/.config/yarn/global/node_modules/@flood/element-core/dist/src/page/ElementHandle.js:56:20)
    at Object.base.apply (/usr/local/share/.config/yarn/global/node_modules/vm2/lib/contextify.js:620:32)
    at ./full.ts:425:25
    at Generator.next (<anonymous>)
    at fulfilled (./full.ts:106:58)
```

Traces for both scripts are the same, only the parts where my test script is named, is replaced with the other name and line number.

**To Reproduce**
Define more than one iteration for your script.

**Expected behavior**
That any iteration runs without errors.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node.js version: 12.18.3
 - Version 1.3.1

**Comment by prodigy7** [comment]
I was able to narrow down the error. It was due to click actions in the last step, which I had not preceded by an await. Afterwards there was no more problem.
