### ISSUE TITLE
Getting Access denied to require 'https'

### ISSUE THREAD

**Issue by mkj28** [flood-io/element#31]
**Describe the bug**
When trying to use https module, getting:
```
{ VMError: Access denied to require 'https'
    at _require (/usr/local/Cellar/element/1.0.4/libexec/lib/node_modules/@flood/element-cli/node_modules/vm2/lib/sandbox.js:195:13)
    at Object.<anonymous> (/var/folders/7l/qqghyvjs20g587ptb1590_3h0000gq/T/flood-element-tmp/test-script-sandbox/flood-chrome.ts:5:15)
    at NodeVM.run (/usr/local/Cellar/element/1.0.4/libexec/lib/node_modules/@flood/element-cli/node_modules/vm2/lib/main.js:419:27)
    at EvaluatedScript.evaluate (/usr/local/Cellar/element/1.0.4/libexec/lib/node_modules/@flood/element-cli/node_modules/@flood/element/src/runtime/EvaluatedScript.js:156:30)
    at new EvaluatedScript (/usr/local/Cellar/element/1.0.4/libexec/lib/node_modules/@flood/element-cli/node_modules/@flood/element/src/runtime/EvaluatedScript.js:42:18)
    at testScriptFactory (/usr/local/Cellar/element/1.0.4/libexec/lib/node_modules/@flood/element-cli/node_modules/@flood/element/src/Element.js:55:16)
    at <anonymous> name: 'VMError', code: 'EDENIED' }
```

**To Reproduce**
import * as https from 'https'

**Expected behavior**
Able to import https 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
Wanted to post some metrics directly to DataDog API.

**Comment by ivanvanderbyl** [comment]
Yep this is because the internal VM is locked down to only load the core DSL. This is a performance optimisation to help constrain memory usage of test scripts.

Would a DD integration on Flood help you if we pushed results to DD for you?

**Comment by mkj28** [comment]
> Would a DD integration on Flood help if we pushed results to DD for you?

DD integration would be 80% success, still would be nice to have the freedom to enable https (even if it means we take a hit on performance)

**Comment by ivanvanderbyl** [comment]
@mkj28 we're going to add support for this in v1.1. Initial work in #40
