### ISSUE TITLE
Running element with a  3rd party NPM module (jimp) crushes after compilation.

### ISSUE THREAD

**Issue by nadavsen2** [flood-io/element#330]
Trying to run element, using a 3rd party node module `jimp` crushes after the compilation step:

````
Running the test with:
- Element v1.3.9
- Node v12.13.0

✔ Script Compiler
  Compiled successfully in 1.02s

Element exited with error
VMError [Error]: Error loading 'events'
    at _requireBuiltin (/Users/nadavsenior/repos/my-element-project/node_modules/vm2/lib/sandbox.js:225:11)
    at _require (/Users/nadavsenior/repos/my-element-project/node_modules/vm2/lib/sandbox.js:291:12)
    at Object.<anonymous> (my-element-project.perf.ts:2023:18)
    at __webpack_require__ (my-element-project.perf.ts:30:30)
    at Object.<anonymous> (my-element-project.perf.ts:597:38)
    at __webpack_require__ (my-element-project.perf.ts:30:30)
    at Object.<anonymous> (my-element-project.perf.ts:219:37)
    at __webpack_require__ (my-element-project.perf.ts:30:30)
    at Object.<anonymous> (my-element-project.perf.ts:171:38)
    at __webpack_require__ (my-element-project.perf.ts:30:30) {
  name: 'VMError',
  code: undefined
}
```


Running on:
 - macOS Catalina 10.15.7
 - node v12.13.0
 - npm v6.12.0
 - jimp version in package.json: ^0.16.1
 - element CLI version in package.json: ^1.3.9

**Comment by mrvdot** [comment]
Having the same issue with `pg`

**Comment by phileba** [comment]
thank @nadavsen2 and @mrvdot, we will have a look at this.
