### ISSUE TITLE
Unexpected error while performing click activity

### ISSUE THREAD

**Issue by mohankumarm2** [flood-io/element#377]
> Error! An unexpected error occurred!
  Error
    at Browser.<anonymous> (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:27:23)
    at Generator.next (<anonymous>)
    at C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:4:12)
    at Browser.descriptor.value (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:23:20)
    at Browser.<anonymous> (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\autoWait.js:37:39)
    at Generator.next (<anonymous>)
    at C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\autoWait.js:8:71
    at new Promise (<anonymous>) Error
    at Browser.<anonymous> (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:27:23)
    at Generator.next (<anonymous>)
    at C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:4:12)
    at Browser.descriptor.value (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\addCallbacks.js:23:20)
    at Browser.<anonymous> (C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\autoWait.js:37:39)
    at Generator.next (<anonymous>)
    at C:\Users\mohankumarm\Desktop\Flood_IO\demoOrangeHRM\node_modules\@flood\element-core\dist\src\runtime\decorators\autoWait.js:8:71
    at new Promise (<anonymous>)
this is a bug,

**To Reproduce**
1. perform the below step on "https://orangehrm-demo-6x.orangehrmlive.com/"
step("Step 4 Click login", async b=>{
		// const var_loginbutton  = await b.findElement(By.xpath('//*[@id="btnLogin"]'))
		// var_loginbutton.click()

		b.click(By.xpath('//*[@id="btnLogin'))
		await b.wait(Until.elementIsVisible(By.visibleText('Dashboard')))
		await b.takeScreenshot()

		// const var_validateLogin = await b.findElement(By.xpath('//*[@id="dashboard-navbar"]/nav/div/ul[1]/li'))
		// console.log(var_validateLogin.text())

	})

**Expected behavior**
Should login to the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/46988179/101870687-1f439780-3ba8-11eb-9a07-cb6780dea80f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node.js version: 7.0.14
 - Element Version 1.3.9

**Comment by HieuLeKMS** [comment]
Hi @mohankumarm2 , I think it's just that you forgot to await your click action. Just put `await` before the action like so `await b.click(By.xpath('//*[@id="btnLogin'))`
