### ISSUE TITLE
Error! An unexpected error occurred! - addCallbacks.js:27:23

### ISSUE THREAD

**Issue by qban** [flood-io/element#396]
**An unexpected error occurred!**

This ErrorMessage occurs not deterministic. usualy after  iteration 2 or 3 once it was running till iteration 8

```
Running the test with:
- Element v1.3.9
- Node v14.15.4

✔ Script Compiler
  Compiled successfully in 221.17ms

+0s info: Starting iteration 1
+0s info:
+0s info: ===> Step 'Step 1: start browser session, go to homepage'
+0s info: ---> Step 'Step 1: start browser session, go to homepage' finished in 3ms
+3s error: page console.error: Failed to load resource: the server responded with a status of 404 (Not Found)
+4s info: page console.info: Messaging without detection successfully executed.
+6s info: Iteration completed in 6s (walltime)
+6s info: Starting iteration 2
> Error! An unexpected error occurred!
  Error
    at Browser.<anonymous> (/Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:27:23)
    at Generator.next (<anonymous>)
    at /Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:4:12)
    at Browser.descriptor.value (/Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:23:20)
    at Object.base.apply (/Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/vm2/lib/contextify.js:620:32)
    at load_home.ts:117:11
    at Generator.next (<anonymous>)
    at load_home.ts:109:71 Error
    at Browser.<anonymous> (/Users/xxxxxxx/Projects/cu/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:27:23)
    at Generator.next (<anonymous>)
    at /Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:4:12)
    at Browser.descriptor.value (/Users/xxxxxxx/Projects/TestScripts/LoadTestPhoenix/node_modules/@flood/element-core/dist/src/runtime/decorators/addCallbacks.js:23:20)
    at Object.base.apply (/Users/d418233/Projects/cu/TestScripts/LoadTestPhoenix/node_modules/vm2/lib/contextify.js:620:32)
    at load_home.ts:117:11
    at Generator.next (<anonymous>)
    at load_home.ts:109:71
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

```
**To Reproduce**

Script load_home.ts

```
import { step, TestSettings, By, Until } from '@flood/element'

export const settings: TestSettings = {
	loopCount: 20
}


export default () => {
	step('Step 1: start browser session, go to homepage', async b => {
  // checked this with several public websites for example
		b.visit('http://www.golem.de')
	})
}
```

installed with `npm install -g element-cli`

Run element local in terminal: 
`>element  run load_home.ts`

**Expected behavior**
Run Script without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Node.js version: v14.15.4
 - Version 1.3.9

**Additional context**

**Comment by qban** [comment]
I investigated a bit more.
started with debug log activated
`DEBUG=* element run load_home.ts`
and get a more detailed ErrorMessage.

**Error: Navigation failed because browser has disconnected!**


Stackoverflow pointed me into the direction that there might be problem withe yield/next - promise/async

_The Navigation failed because browser has disconnected error usually means that the node scripts that launched Puppeteer ends without waiting for the Puppeteer actions to be completed._ 

(https://stackoverflow.com/questions/54527982/why-is-puppeteer-reporting-unhandledpromiserejectionwarning-error-navigation)
