### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by sed-i** [flood-io/element#572]
**Describe the bug**
Script fails to run with node 17.

**To Reproduce**

Try running the example script.

```
$ npx @flood/element-cli run example.ts
Running example.ts (1 of 1) with
- Element v2.0.4
- Node v17.6.0

● Script Compiler █████████████████████████ compiling (0%)  
 

> Error! An unexpected error occurred!
  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/loader-runner/lib/LoaderRunner.js:221:10) Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/ubuntu/.npm/_npx/b1911d56a05d7b9b/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
```
**Expected behavior**
The example script runs.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.3 LTS
- Node.js version: v17.6.0
- Version v2.0.4

**Additional context**
The same thing works with node 16 and older:
```
$ sudo snap refresh node --channel=16/stable
node (16/stable) 16.14.0 from OpenJS Foundation (iojs✓) refreshed
$ element run example.ts
Running example.ts (1 of 1) with
- Element v2.0.4
- Node v16.14.0

✔ Script Compiler
  Compiled successfully in 242.70ms

^C⠋ Iteration 1 
    ✓ Step '1. Start' passed (1,000ms)
      Screenshot saved in /home/ubuntu/tmp/element-results/example/2022-03-08T035040.856Z/screenshots/265RQXipbGkrAR9enKw0xPpxYty.jpg
    ⠋ Step '2. Age' is running ...
```

**Comment by mjvdende** [comment]
also fails in node v18 with same issue
