### ISSUE TITLE
Unable getting init example working

### ISSUE THREAD

**Issue by aandren** [flood-io/element#616]
**Describe the bug**
Following the how to on the elemtns website.

**To Reproduce**
Follow the instructions on:
https://element.flood.io/docs/start/init

**Screenshots**
<img width="1429" alt="Screenshot 2023-01-30 at 22 35 45" src="https://user-images.githubusercontent.com/2334378/215600469-ca463980-0b5e-4ea9-abb2-dae2e5a63b62.png">

**Desktop (please complete the following information):**
Im runining
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.2.0
Thread model: posix

- Node.js version: 18.13.0
- Version v2.0.4

**Comment by jbassendine** [comment]
Same issue for me

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Install nvm using cURL command
2. nvm install node (installs v19.6.0)
3. nvm use node
4. npm -g install element-cli
5. make project folder and cd into it
6. element init
7. element run flood-element.perf.ts --no-headless

**Expected behavior**
Expected the template script to run 

**Stacktrace**

Running flood-element.perf.ts (1 of 1) with
- Element v2.0.4
- Node v19.6.0

Script Compiler █████████████████████████ compiling (0%)   

> Error! An unexpected error occurred!
  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10) Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md


**Desktop (please complete the following information):**

- OS: Fedora 36
- Node.js version: 19.6.0
- Version 2.0.4
