### ISSUE TITLE
Error after initial setup, "digital envelope routines::unsupported"

### ISSUE THREAD

**Issue by jbassendine** [flood-io/element#617]
**Describe the bug**

**To Reproduce**

1. Install nvm using cURL command
2. nvm install node (installs v19.6.0)
3. nvm use node
4. npm -g install element-cli
5. make project folder and cd into it
6. element init
7. element run flood-element.perf.ts --no-headless

**Expected behavior**
Expected the template script to run 

**Stacktrace**

Running flood-element.perf.ts (1 of 1) with
- Element v2.0.4
- Node v19.6.0

Script Compiler █████████████████████████ compiling (0%)   

> Error! An unexpected error occurred!
  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10) Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/james/.nvm/versions/node/v19.6.0/lib/node_modules/element-cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

**Desktop (please complete the following information):**

- OS: Fedora 36
- Node.js version: 19.6.0
- Version 2.0.4

**Comment by jbassendine** [comment]
Other issues open, will close this and post there instead:

https://github.com/flood-io/element/issues/616
