### ISSUE TITLE
Fresh install crashes

### ISSUE THREAD

**Issue by stacker60** [flood-io/element#622]
**Describe the bug**
After installing Element under Windows 11, initial script crashes.

**To Reproduce**

1. > mkdir Element
2. > cd Element
3. > element init
4. > element run Element.perf.ts

**Expected behavior**
Not this:

Running Element.perf.ts (1 of 1) with
- Element v2.0.4
- Node v18.16.0

* Script Compiler █████████████████████████ compiling (0%)

> Error! An unexpected error occurred!
  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\loader-runner\lib\LoaderRunner.js:221:10) Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Jon\AppData\Roaming\npm\node_modules\element-cli\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
this is a bug, please report it here https://github.com/flood-io/element/issues/new?template=bug_report.md

**Screenshots**

**Desktop (please complete the following information):**

- OS: Microsoft Windows 11 Pro
- Node.js version: [e.g. 9.4] 18.16.0
- Version [e.g. 1.0.2] 2.0.4

**Additional context**
[Element.zip](https://github.com/flood-io/element/files/11522592/Element.zip)

**Comment by okHadi** [comment]
Same behavior encountered. Downgrading to node version 16 works.
