### ISSUE TITLE
Support importing script helpers from other node modules

### ISSUE THREAD

**Issue by ivanvanderbyl** [flood-io/element#71]
# Benefit:

Make it possible to include external node packages in the test VM at runtime. 

## Technical considerations

* Refactor the compiler to support loading packages
* Run npm install in the sandbox directory
* Allow uploading a package or syncing from GitHub
* Compile everything into the VM

**Comment by dorrogeray** [comment]
I have a question. Will this resolve the problem of not being able to use `const fs = require('fs');` in the test scripts? Currently it crashes the `element run test.ts` command.

```
jb@jb-ntb:~/projects/xxx/test/performance (develop)$ element run test.ts
+0s info: workRootPath: /home/jb/projects/xxx/test/performance/tmp/element-results/test/2020-02-09T115832.614Z
+0s info: testDataPath: /home/jb/projects/xxx/test/performance
Module resolve paths: node_modules

✖ Script Compiler
  Compiled with some errors in 143.30ms

Element exited with error
Error: Hash: 0bbeaa95cfde17652a7b
Version: webpack 4.41.5
Time: 145ms
Built at: 02/09/2020 12:58:32 PM
        Asset      Size  Chunks                   Chunk Names
    bundle.js  11.5 KiB       0  [emitted]        main
bundle.js.map  12.6 KiB       0  [emitted] [dev]  main
Entrypoint main = bundle.js bundle.js.map
[0] ./test.ts 1.71 KiB {0} [built]
[1] /home/jb/.config/yarn/global/node_modules/process/browser.js 5.29 KiB {0} [built]
[2] external "@flood/element" 42 bytes {0} [built]

ERROR in ./test.ts
Module not found: Error: Can't resolve 'fs' in '/home/jb/projects/xxx/test/performance'
resolve 'fs' in '/home/jb/projects/xxx/test/performance'
  Parsed request is a module
  using description file: /home/jb/projects/xxx/test/performance/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/jb/projects/xxx/test/node_modules doesn't exist or is not a directory
      /home/jb/projects/node_modules doesn't exist or is not a directory
      /home/jb/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/jb/projects/xxx/test/performance/node_modules
        using description file: /home/jb/projects/xxx/test/performance/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /home/jb/projects/xxx/node_modules
        using description file: /home/jb/projects/xxx/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/jb/projects/xxx/test/performance/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/jb/projects/xxx/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/jb/projects/xxx/test/performance/node_modules/fs doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/jb/projects/xxx/node_modules/fs doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/jb/projects/xxx/test/performance/node_modules/fs.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/jb/projects/xxx/node_modules/fs.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/jb/projects/xxx/test/performance/node_modules/fs.js doesn't exist
              /home/jb/projects/xxx/node_modules/fs.js doesn't exist
            as directory
              /home/jb/projects/xxx/test/performance/node_modules/fs doesn't exist
            as directory
              /home/jb/projects/xxx/node_modules/fs doesn't exist
[/home/jb/projects/xxx/test/node_modules]
[/home/jb/projects/node_modules]
[/home/jb/node_modules]
[/home/node_modules]
[/node_modules]
[/home/jb/projects/xxx/test/performance/node_modules/fs]
[/home/jb/projects/xxx/node_modules/fs]
[/home/jb/projects/xxx/test/performance/node_modules/fs.ts]
[/home/jb/projects/xxx/node_modules/fs.ts]
[/home/jb/projects/xxx/test/performance/node_modules/fs.js]
[/home/jb/projects/xxx/node_modules/fs.js]
 @ ./test.ts 12:11-24
    at /home/jb/.config/yarn/global/node_modules/@flood/element-compiler/dist/src/index.js:103:36
    at finalCallback (/home/jb/.config/yarn/global/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/jb/.config/yarn/global/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jb/.config/yarn/global/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/jb/.config/yarn/global/node_modules/tapable/lib/Hook.js:154:20)
    at /home/jb/.config/yarn/global/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/jb/.config/yarn/global/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/jb/.config/yarn/global/node_modules/webpack/lib/Compiler.js:298:10
    at /home/jb/.config/yarn/global/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jb/.config/yarn/global/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
```

This is related to https://github.com/flood-io/element/issues/104, as I have tried importing `dotenv` but got a crash similar to this one.. After some debugging, I realized its not possible to import the `fs` itself.

**Comment by ivanvanderbyl** [comment]
@dorrogeray sorry about the delay getting back to you. `fs` should work now in the latest release of `element-cli`

**Comment by ivanvanderbyl** [comment]
This is now supported.
