### ISSUE TITLE
Unable to install element on Windows 10

### ISSUE THREAD

**Issue by tswiftma** [flood-io/element#82]
**Describe the bug**
Unable to install flood element on Windows 10

**To Reproduce**
1. On Win10 (ver 1703 OS build 15063.1058) with Node (v10.16.3) and NPM (6.9.0) already installed
2. Attempt to install flood element (npm install -g @flood/element-cli)
3. Error received (repro'd on 2 different machines)

$ npm install -g @flood/element-cli
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN rollback Rolling back pify@3.0.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\tswift\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\path-type\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@flood\element-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! path C:\Users\tswift\AppData\Roaming\npm\node_modules\@flood\element-cli\dist\index.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\tswift\AppData\Roaming\npm\node_modules\@flood\element-cli\dist\index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tswift\AppData\Roaming\npm-cache\_logs\2019-09-03T20_24_35_014Z-debug.log

**Comment by tswiftma** [comment]
Working after updating today. Still seeing the below error though

> Error! Checking for updates failed
Error: Distribution tag stable is not available
    at getMostRecent (C:\Users\tswift\AppData\Roaming\npm\node_modules\@flood\element-cli\node_modules\update-check\index.js:140:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
