### ISSUE TITLE
Error: package.json not found in path on init

### ISSUE THREAD

**Issue by clintivy** [flood-io/element#95]
**Describe the bug**
Via `element init <project name>` in v1.0.10-beta.21 of the element cli on Mac OSX Catalina.

**To Reproduce**
1. Open Terminal/Shell app
2. run command ```element init my-project-name```
3. look at errors
**Expected behavior**
presumably a successfully created project
**Error Dump**
Error! An unexpected error occurred!
  Error: package.json not found in path
    at Object.findRoot [as default] (/Users/username/.config/yarn/global/node_modules/@flood/element-cli/dist/index.js:40788:11)
    at TestEnv.initializing (/Users/username/.config/yarn/global/node_modules/@flood/element-cli/dist/index.js:12898:67)
    at Object.<anonymous> (/Users/username/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/username/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/username/.config/yarn/global/node_modules/run-async/index.js:24:19
    at /Users/username/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:425:13
    at processImmediate (internal/timers.js:444:21) Error: package.json not found in path
    at Object.findRoot [as default] (/Users/username/.config/yarn/global/node_modules/@flood/element-cli/dist/index.js:40788:11)
    at TestEnv.initializing (/Users/username/.config/yarn/global/node_modules/@flood/element-cli/dist/index.js:12898:67)
    at Object.<anonymous> (/Users/username/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:424:27)
    at /Users/username/.config/yarn/global/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/username/.config/yarn/global/node_modules/run-async/index.js:24:19
    at /Users/username/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:425:13
    at processImmediate (internal/timers.js:444:21)
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.1 (19B88)
 - Node.js version: 13.3.0
 - Version 1.0.10-beta.21

**Additional context**

**Comment by ivanvanderbyl** [comment]
This should be fixed in the latest beta `1.0.10-beta.39`. Please upgrade with:

Yarn: `yarn global upgrade @flood/element-cli@beta`
Or NPM: `npm -g install @flood/element-cli@beta`
